"""Added layout matrix

Revision ID: ea69e8893eb0
Revises: 10ef3e0d4887
Create Date: 2025-12-02 20:39:51.434659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea69e8893eb0'
down_revision = '10ef3e0d4887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('layout_matrix', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_column('layout_matrix')

    # ### end Alembic commands ###
